/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/DetailT-v1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/DetailT-v1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.About_Me_Pictures.geometry} material={materials['MergedBake_Baked.010']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.detail_Baked.geometry} material={materials['MergedBake_Baked.010']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Project_One.geometry} material={materials['MergedBake_Baked.010']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Project_Four.geometry} material={materials['MergedBake_Baked.010']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Project_Two.geometry} material={materials['MergedBake_Baked.010']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Project_Three.geometry} material={materials['MergedBake_Baked.010']} rotation={[Math.PI / 2, 0, 0]} />
      {/* <mesh geometry={nodes.about_me_text.geometry} material={materials['MergedBake_Baked.010']} rotation={[Math.PI / 2, 0, 0]} /> */}
    </group>
  )
}

useGLTF.preload('/DetailT-v1.glb')
